server:
  port: 8085
spring:
  application:
    name: operation-service
  datasource:
    url: mongodb://mongodb:27017/operations
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
  profiles:
    active: default
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
