services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: lotfi
      POSTGRES_PASSWORD: 12345
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  postgrescl:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: lotfi
      POSTGRES_PASSWORD: 12345
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgrescl
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  mysqldb:
    restart: unless-stopped
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: "mysqldb"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stdn
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring
  eureka-server:
    image: lotfi07/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
  apigw:
    image: amigoscode/apigw:latest
    container_name: apigw
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server
  client:
    image: amigoscode/client:latest
    container_name: client
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgrescl
    depends_on:
      - zipkin
      - postgrescl
      - rabbitmq
  compte:
    image: amigoscode/compte:latest
    container_name: compte
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - mysqldb
    depends_on:
      - zipkin
      - mysqldb
      - rabbitmq
  operation:
    image: lotfi07/operation:latest
    container_name: operation
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - mongodb
    depends_on:
      - zipkin
      - mongodb
      - rabbitmq
  notification:
    image: amigoscode/notification:latest
    container_name: notification
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
  postgrescl:
    driver: bridge

volumes:
  postgres:
  pgadmin: