server:
    port: 8081

spring:
    application:
        name: api-gateway
    zipkin:
        base-url: http://localhost:9411
    cloud:
       gateway:
          routes:
            - id: client
              uri: lb://CLIENT
              predicates:
                - Path=/api/v1/clients/**
            - id: compte
              uri: lb://COMPTE
              predicates:
                - Path=/api/v1/comptes/**
            - id: operation
              uri: lb://OPERATION
              predicates:
                - Path=/api/v1/operations/**
            - id: notification
              uri: lb://NOTIFICATION
              predicates:
                - Path=/api/v1/notifications/**

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true